export { default as Header } from './Header/Header'
export { default as About } from './About/About'
export { default as ContactUs } from './ContactUs/ContactUs'
export { default as AllNav } from './AllNav/AllNav'
export { default as Footer } from './Footer/Footer'
export { default as OngoingProjects } from './OngoingProjects/OngoingProjects'
export { default as Previous } from './Previous/Previous'
export { default as Services } from './Services/Services'
export { default as Specification } from './Specification/Specification'
export { default as UnderHeader } from './UnderHeader/UnderHeader'
export { default as PopupProject } from './Popup/Popup'
export { default as Language } from './Language/Language'
export { default as ButtonPlus } from './UI/ButtonPlus/ButtonPlus'
export { default as NavMenu } from './UI/NavMenu/NavMenu'

